services:
  service-b:
    build:
      context: ./service-b
    environment:
      - PORT=8001
      - DELAY_MS=0 # was 5000
      - FAIL_AFTER_STORE_ONCE=1
    ports:
      - "8001:8001"

  service-a:
    build:
      context: ./service-a
    environment:
      - PORT=8000
      - SERVICE_B_BASE_URL=http://service-b:8001
    depends_on:
      - service-b
    ports:
      - "8000:8000"
